"""Real-time streaming RAG with hybrid generation/regurgitation."""

import sys
from typing import Iterable, List, Optional, Tuple
from dataclasses import dataclass

import numpy as np

from kiwix_chat.models import Chunk
from kiwix_chat.rag.retriever import RAGRetriever
from kiwix_chat.rag.vector_store import get_vector_store
from kiwix_chat.rag.token_buffer import TokenBuffer
from kiwix_chat.rag.embeddings import generate_embedding, generate_embeddings_batch
from kiwix_chat.chat.ollama import ollama_stream_chat


@dataclass
class StreamingContext:
    """Context for streaming generation."""
    query: str
    chunks: List[Chunk]
    token_buffer: TokenBuffer
    source_texts: List[str]  # Original text for exact copying


def fast_retrieve(query: str, zim_file_path: str, top_k: int = 5) -> List[Chunk]:
    """Fast retrieval using embedding model directly - NO INDEX REQUIRED.
    
    Like Perplexica: embedding model finds relevant content → tokenize → use
    
    Args:
        query: User query
        zim_file_path: Path to ZIM file
        top_k: Number of chunks to return
        
    Returns:
        List of relevant Chunk objects
    """
    # Generate query embedding (this is what finds relevant content)
    query_embedding = generate_embedding(query, is_query=True)
    
    # Read articles from ZIM and process them
    from kiwix_chat.rag.zim_reader import list_zim_articles, read_zim_article
    from kiwix_chat.rag.chunker import chunk_article
    
    all_chunks = []
    article_count = 0
    max_articles = 500  # Process more articles for better results
    
    print(f"[rag] Using embedding model to find relevant content from ZIM...", file=sys.stderr)
    
    for title, href in list_zim_articles(zim_file_path):
        if article_count >= max_articles:
            break
        
        article_text = read_zim_article(zim_file_path, href)
        if not article_text:
            continue
        
        # Chunk article
        chunks = chunk_article(article_text, title, href, max_chunk_size=500, overlap=50)
        all_chunks.extend(chunks)
        article_count += 1
        
        if article_count % 50 == 0:
            print(f"[rag] Processed {article_count} articles, {len(all_chunks)} chunks...", file=sys.stderr)
    
    if not all_chunks:
        return []
    
    # Generate embeddings for chunks using embedding model (this is the "index")
    print(f"[rag] Embedding model generating embeddings for {len(all_chunks)} chunks...", file=sys.stderr)
    chunk_texts = [chunk.text for chunk in all_chunks]
    chunk_embeddings = generate_embeddings_batch(chunk_texts, batch_size=64, show_progress=True, is_query=False)
    
    # Find most similar chunks using cosine similarity
    query_vec = np.array(query_embedding)
    scored_chunks = []
    
    for chunk, embedding in zip(all_chunks, chunk_embeddings):
        chunk_vec = np.array(embedding)
        # Cosine similarity
        similarity = np.dot(query_vec, chunk_vec) / (np.linalg.norm(query_vec) * np.linalg.norm(chunk_vec))
        scored_chunks.append((similarity, chunk))
    
    # Sort by similarity and return top_k
    scored_chunks.sort(key=lambda x: -x[0])
    
    print(f"[rag] Found {len(scored_chunks)} chunks, returning top {top_k} most relevant", file=sys.stderr)
    
    return [chunk for _, chunk in scored_chunks[:top_k]]


def stream_hybrid_response(
    model: str,
    query: str,
    messages: List[dict],
    zim_file_path: str,
    max_tokens: int = 2048
) -> Iterable[str]:
    """Stream response with hybrid generation/regurgitation.
    
    The LLM can use special markers:
    - <QUOTE>text</QUOTE> - indicates exact copy from source
    - Normal text - generated by LLM
    
    Args:
        model: LLM model name
        query: User query
        messages: Chat messages
        zim_file_path: Path to ZIM file
        max_tokens: Max tokens in buffer
        
    Yields:
        Text chunks as they're generated
    """
    # Fast retrieval (real-time)
    try:
        chunks = fast_retrieve(query, zim_file_path, top_k=5)
        if not chunks:
            # No chunks found, just stream normal generation
            yield from ollama_stream_chat(model, messages)
            return
    except Exception as e:
        # If retrieval fails, fall back to normal generation
        import sys
        print(f"[rag] Retrieval failed: {e}, using normal generation", file=sys.stderr)
        try:
            yield from ollama_stream_chat(model, messages)
        except Exception as stream_err:
            yield f"[Error: {stream_err}]"
        return
    
    # Tokenize chunks in real-time
    token_buffer = TokenBuffer(max_tokens=max_tokens, pruning_strategy="relevance")
    relevance_scores = [1.0 - (i * 0.15) for i in range(len(chunks))]
    token_buffer.add_chunks(chunks, relevance_scores)
    
    # Get source texts for exact copying - create a searchable fact database
    source_texts = [chunk.text for chunk in chunks]
    combined_source = "\n\n".join([f"=== {chunk.article_title} ===\n{chunk.text}" for chunk in chunks])
    
    # Extract key facts from source for matching (dates, names, locations, numbers)
    import re
    fact_patterns = []
    for source in source_texts:
        # Extract dates (various formats)
        dates = re.findall(r'\b(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},?\s+\d{4}\b', source)
        # Extract years
        years = re.findall(r'\b(19|20)\d{2}\b', source)
        # Extract locations (capitalized words that might be places)
        locations = re.findall(r'\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*\b', source)
        fact_patterns.extend(dates + years + locations[:10])  # Limit locations
    
    # Create fact lookup: map keywords to exact source text
    fact_lookup = {}
    for source in source_texts:
        source_lower = source.lower()
        for fact in fact_patterns:
            if fact.lower() in source_lower:
                # Find the sentence containing this fact
                sentences = re.split(r'[.!?]+', source)
                for sentence in sentences:
                    if fact.lower() in sentence.lower():
                        fact_lookup[fact.lower()] = sentence.strip()
                        break
    
    enhanced_messages = messages.copy()
    system_msg = {
        "role": "system",
        "content": f"""Use [FACT:keyword] for facts.

Source material:
{combined_source[:3500]}"""
    }
    enhanced_messages = [msg for msg in enhanced_messages if msg.get("role") != "system"]
    enhanced_messages.insert(0, system_msg)
    
    # Stream generation with real-time fact replacement
    buffer = ""
    fact_pattern = re.compile(r'\[FACT:([^\]]+)\]')
    output_pos = 0  # Position in buffer that we've yielded up to
    
    for chunk in ollama_stream_chat(model, enhanced_messages):
        buffer += chunk
        
        # Process complete markers
        while True:
            matches = [m for m in fact_pattern.finditer(buffer) if m.end() <= len(buffer)]
            if not matches:
                break
            
            # Process first marker
            match = matches[0]
            if match.start() < output_pos:
                break  # Already processed
            
            keyword = match.group(1).strip().lower()
            
            # Find in source (flexible matching - handle numbers, dates, etc.)
            exact_text = None
            keyword_normalized = re.sub(r'\s+', ' ', keyword.strip())
            
            for source in source_texts:
                source_lower = source.lower()
                # Try exact keyword match first
                if keyword_normalized in source_lower:
                    sentences = re.split(r'[.!?]+', source)
                    for sentence in sentences:
                        if keyword_normalized in sentence.lower():
                            exact_text = sentence.strip()
                            break
                    if exact_text:
                        break
                
                # Try word-by-word match for multi-word keywords
                if not exact_text and ' ' in keyword_normalized:
                    words = keyword_normalized.split()
                    if len(words) >= 2:
                        sentences = re.split(r'[.!?]+', source)
                        for sentence in sentences:
                            sentence_lower = sentence.lower()
                            if all(word in sentence_lower for word in words):
                                exact_text = sentence.strip()
                                break
                        if exact_text:
                            break
            
            if exact_text:
                # Yield text before marker
                if match.start() > output_pos:
                    yield buffer[output_pos:match.start()]
                
                # Yield replacement
                yield exact_text
                
                # Remove processed part from buffer
                buffer = buffer[match.end():]
                output_pos = 0  # Reset since we removed from buffer
            else:
                # No match - yield up to marker, keep marker
                if match.start() > output_pos:
                    yield buffer[output_pos:match.start()]
                output_pos = match.start()
                break  # Exit loop, continue accumulating
        
        # Yield accumulated text (in chunks to avoid delay)
        if len(buffer) > output_pos + 200:
            # Check for pending markers
            pending = [m for m in fact_pattern.finditer(buffer) if m.start() >= output_pos]
            if pending:
                # Yield up to first pending marker
                next_start = pending[0].start()
                if next_start > output_pos:
                    yield buffer[output_pos:next_start]
                    output_pos = next_start
            else:
                # No markers, yield all
                yield buffer[output_pos:]
                buffer = ""
                output_pos = 0
    
    # Yield remaining buffer
    if output_pos < len(buffer):
        # Process any remaining markers
        remaining = buffer[output_pos:]
        processed = fact_pattern.sub(
            lambda m: next(
                (s.strip() for source in source_texts 
                 for s in re.split(r'[.!?]+', source) 
                 if m.group(1).strip().lower() in s.lower()),
                m.group(0)  # Fallback: return marker as-is
            ),
            remaining
        )
        yield processed


def simple_rag_query(
    model: str,
    query: str,
    zim_file_path: str,
    conversation_history: Optional[List[dict]] = None,
    system_prompt: Optional[str] = None
) -> Iterable[str]:
    """Simple RAG query - one function call.
    
    Fast real-time flow:
    1. Embedding model finds relevant chunks (fast)
    2. Chunks tokenized in real-time
    3. Stream generation with source context
    4. LLM can generate or quote exact facts
    
    Args:
        model: LLM model name
        query: User query
        zim_file_path: Path to ZIM file
        conversation_history: Optional conversation history
        system_prompt: Optional system prompt
        
    Yields:
        Response text chunks (streaming in real-time)
    """
    messages = conversation_history.copy() if conversation_history else []
    
    # Add system prompt if provided
    if system_prompt:
        # Check if system message exists, if not add it
        if not messages or messages[0].get("role") != "system":
            messages.insert(0, {"role": "system", "content": system_prompt})
        else:
            messages[0]["content"] = system_prompt
    
    messages.append({"role": "user", "content": query})
    
    yield from stream_hybrid_response(model, query, messages, zim_file_path)

